#!/usr/bin/env bash
# Double the number of webservers

apt update -y
apt install nginx -y
echo "Holberton School" > /var/www/html/index.html
sed -i "/server_name _/a \       rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n" /etc/nginx/sites-available/default
sed -i "/location /a \       error_page 404 /code_404.html;\n" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/code_404.html
sed -i "/location /a \       add_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-available/default
service nginx restart
