#!/usr/bin/env bash
# Write a Bash script that displays Holberton School 10 times
# You must use the while loop (for and until are forbidden)

let i=0
while ((i<10))
do
	 echo "Holberton School"
	 ((i++))
done
