#!/usr/bin/env bash
# Write a Bash script that displays Holberton School 10 times
# You must use the until loop (for and while are forbidden)

let i=0
until ((i>=10))
do
	echo "Holberton School"
	((i++))
done
