#!/usr/bin/env bash
# Write a Bash script that displays Holberton School 10 times
# but for the 9th iteration, displays Holberton School and then Hi on a new line

let i=0
while ((i<10))
do
 	if ((i==3))
           then
		echo "bad luck"
	elif ((i==7))
	   then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((i++))
done