#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
# You must use the while loop (for and until are forbidden)

let h=0
while ((h<13))
do
	echo "Hour: $h"
	let m=1
	while ((m<60))
	do
		echo "$m"
		((m++))
	done
	((h++))
done
