#!/usr/bin/env bash
# Run Nginx as Nginx
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i "1iuser nginx;" /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
su -c "service nginx restart" nginx
